# Generated by Django 4.0 on 2021-12-10 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nombre_completo', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
                ('empresa', models.CharField(max_length=75)),
                ('ubicacion', models.CharField(max_length=150)),
                ('mercado', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_finalisacion', models.DateTimeField()),
                ('administrador_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creador', to='app.administradores')),
                ('administrador_encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encargado', to='app.administradores')),
            ],
        ),
        migrations.CreateModel(
            name='cotisaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuarios')),
            ],
        ),
    ]
