# Generated by Django 4.0 on 2021-12-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_servicios_alter_cotizaciones_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
